// Package policy renders the Tetragon TracingPolicies from sensor.yaml. The
// file filters have to run in the kernel — a Python program opens thousands
// of library files at start-up — so they are policy, not shipper, settings.
// Connections and listening sockets are taken whole; the shipper keeps only
// agents' and labels them.
package policy

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Diana-Secarea/advanced-selenne-agents/sensor/internal/config"
)

// q quotes a value for YAML (a JSON string is a valid YAML scalar).
func q(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

func list(indent string, values []string) string {
	var b strings.Builder
	for _, v := range values {
		b.WriteString(indent + "- " + q(v) + "\n")
	}
	return b.String()
}

func header(name, comment string) string {
	return "# Generated by selenne-sensor from sensor.yaml — edit that, not this.\n# " + comment + "\n" +
		"apiVersion: cilium.io/v1alpha1\nkind: TracingPolicy\nmetadata:\n  name: " + name + "\nspec:\n  kprobes:\n"
}

// Files: every successful open outside the skipped folders and file types,
// plus the sensitive files wherever they are. security_file_open is the LSM
// hook: it runs after the permission check, so it sees opens that happened.
func Files(f config.Files) string {
	var b strings.Builder
	b.WriteString(header("selenne-files", "Agents' file activity; system folders and library files stay in the kernel."))
	b.WriteString("  - call: \"security_file_open\"\n    syscall: false\n    args:\n    - index: 0\n      type: \"file\"\n    selectors:\n")
	if len(f.Sensitive) > 0 {
		b.WriteString("    - matchArgs:\n      - index: 0\n        operator: \"Postfix\"\n        values:\n")
		b.WriteString(list("        ", f.Sensitive))
	}
	b.WriteString("    - matchArgs:\n")
	if len(f.SkipPrefixes) > 0 {
		b.WriteString("      - index: 0\n        operator: \"NotPrefix\"\n        values:\n")
		b.WriteString(list("        ", f.SkipPrefixes))
	}
	if len(f.SkipSuffixes) > 0 {
		b.WriteString("      - index: 0\n        operator: \"NotPostfix\"\n        values:\n")
		b.WriteString(list("        ", f.SkipSuffixes))
	}
	if len(f.SkipPrefixes) == 0 && len(f.SkipSuffixes) == 0 {
		b.WriteString("      - index: 0\n        operator: \"Prefix\"\n        values:\n        - \"/\"\n")
	}
	return b.String()
}

func Connect() string {
	return header("selenne-connect", "Every outbound TCP connection; the shipper keeps agents' and labels them.") +
		"  - call: \"tcp_connect\"\n    syscall: false\n    args:\n    - index: 0\n      type: \"sock\"\n"
}

// Listen: which program listens on which port, so a local connection is
// named after what it reached ("qdrant", not just 127.0.0.1:6333).
func Listen() string {
	return header("selenne-listen", "Programs starting to listen, for naming local connections.") +
		"  - call: \"inet_csk_listen_start\"\n    syscall: false\n    args:\n    - index: 0\n      type: \"sock\"\n"
}

// Write renders every policy into dir (Tetragon's --tracing-policy-dir),
// removing a file policy left over from a config that has since disabled it.
func Write(cfg config.Config, dir string) ([]string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	files := map[string]string{"selenne-connect.yaml": Connect(), "selenne-listen.yaml": Listen()}
	if cfg.Files.Enabled {
		files["selenne-files.yaml"] = Files(cfg.Files)
	} else {
		os.Remove(filepath.Join(dir, "selenne-files.yaml"))
	}
	var written []string
	for name, body := range files {
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return written, fmt.Errorf("%s: %w", path, err)
		}
		written = append(written, path)
	}
	return written, nil
}
