#!/usr/bin/env bash
# Copy Selenne's look & feel into frontend/assets/selenne/ so the Agents
# console renders exactly like the SIEM on its own — directly on :4319, in
# dev, or behind nginx — instead of depending on Selenne's /assets/ being
# served on the same origin.
#
#   scripts/sync-selenne-ui.sh [path/to/advanced-ai-siem]   (default: ~/wazuh)
#
# Copied as-is:   style.css, product-switch.js
# Built:          ui.js — only the presentation sections of Selenne's app.js
#                 (background, animations, helpers). SIEM behaviour — list
#                 managers, collector downloads, the SIEM auth redirect, its
#                 banners — is left out on purpose.
# Re-run after changing Selenne's UI; never edit the copies by hand.
set -euo pipefail

SELENNE_REPO="${1:-$HOME/wazuh}"
SRC="$SELENNE_REPO/wazuh-monorepo/apps/frontend/assets"
DEST="$(cd "$(dirname "$0")/.." && pwd)/frontend/assets/selenne"

for f in style.css product-switch.js app.js; do
  [ -f "$SRC/$f" ] || { echo "missing $SRC/$f — pass the advanced-ai-siem checkout path" >&2; exit 1; }
done
mkdir -p "$DEST"
cp "$SRC/style.css" "$SRC/product-switch.js" "$DEST/"

REV="$(git -C "$SELENNE_REPO" rev-parse --short HEAD 2>/dev/null || echo unknown)"
if [ -n "$(git -C "$SELENNE_REPO" status --porcelain -- wazuh-monorepo/apps/frontend/assets 2>/dev/null)" ]; then
  REV="$REV+dirty"   # copied from uncommitted Selenne UI changes
fi
python3 - "$SRC/app.js" "$DEST/ui.js" "$REV" <<'PY'
import re, sys
src, dest, rev = sys.argv[1:4]
KEEP = ("Particle constellation background", "Scroll reveal", "Animated counters",
        "Card cursor glow", "3D tilt", "Fill score bars when visible", "Shared helpers",
        "Page transitions", "Nav shrink on scroll", "Close modals on overlay click",
        "Cinematic cohesion layer")
lines = open(src, encoding="utf-8").read().split("\n")
marker = re.compile(r"^/\* (?:-{6,}|={6,})")
sections, cur = [], None
for line in lines:
    if marker.match(line):
        cur = [line]
        sections.append(cur)
    elif cur is not None:
        cur.append(line)
kept, found = [], set()
for sec in sections:
    head = sec[0] if not sec[0].startswith("/* ===") else (sec[1] if len(sec) > 1 else "")
    title = re.sub(r"^/\*\s*-+\s*|\s*-+\s*(\*/)?\s*$", "", head).strip()
    match = next((k for k in KEEP if title.startswith(k)), None)
    if match:
        kept.append("\n".join(sec).rstrip())
        found.add(match)
missing = set(KEEP) - found
if missing:
    sys.exit(f"sections not found in app.js: {sorted(missing)} — update KEEP")
body = "\n\n".join(kept)
for forbidden in ("/api/", "makeNavManager", "location.href = \"/login.html\""):
    if forbidden in body:
        sys.exit(f"extracted ui.js still contains {forbidden!r} — a SIEM section leaked in")
open(dest, "w", encoding="utf-8").write(
    "/* GENERATED by scripts/sync-selenne-ui.sh from Selenne app.js @ " + rev + " — do not edit.\n"
    "   Presentation only: background, animations, helpers. */\n\n" + body + "\n")
print(f"ui.js: {len(kept)} sections from app.js @ {rev}")
PY
echo "synced Selenne UI into $DEST"
